version: "3"
services:
  cutechan:
    image: cutechan
    ports:
      - "8001:8001"
    networks:
      - db
    volumes:
      - "./cutechan.toml:/cutechan.toml"
      - "./dist:/dist"
    environment:
      - TZ=Europe/Moscow

  kpopnet:
    image: kpopnet
    ports:
      - "8002:8002"
    networks:
      - db
    volumes:
      - "./kpopnet.toml:/kpopnet.toml"
    environment:
      - TZ=Europe/Moscow

networks:
  db:
    external: true
